services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
  php:
    build: ./php
    container_name: php-server
    ports:
      - 9000
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
